version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Running build step
      - npm run build
      - echo Running tests
      - npm test
artifacts:
  files:
    - '**/*'
  discard-paths: no
